name: Android Feature Branch CI Workflow

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  test:
    name: Run unit test & instrumentation test, and upload the reports as artifact
    runs-on: macos-latest

    steps:
      - name: Checkout to current repository
        uses: actions/checkout@v1

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run unit test
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Run instrumentation test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          profile: Nexus 6
          avd-name: test
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace

      - name: Upload the reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/reports
